

services:
  nginx:
    image: registry.cn-shanghai.aliyuncs.com/wukongim/nginx:1.27.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "15001:5001" # api端口
      - "15100:5100" # tcp端口
      - "15200:5200" # ws端口
      - "15300:5300" # manager端口
      - "15172:5172" # demo端口